apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rstudio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rstudio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rstudio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.storage.mountPath }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: application-password
                  name: {{ include "rstudio.fullname" . }}
            - name: USER
              value: {{ .Values.username }}
            {{- if .Values.serviceAccount.sudoEnabled }}
            - name: ROOT
              value: "TRUE"
            {{- end }}
            - name: OPENBLAS_NUM_THREADS
              value: "{{ toString .Values.openblasNumThreads }}"
            # To enable updating the image: https://github.com/kubernetes/kubernetes/issues/33664
            - name: RELEASE_DATE
              value: "{{ now }}"
            {{- if .Values.service.shinyPort }}
            - name: ADD
              value: "SHINY"
            {{- end }}
            {{- range .Values.extraEnvs }}
            - name: {{ toString .name }}
              value: {{ toString .value }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.service.shinyPort }}
            - name: http-{{ .Values.service.shinyPort }}
              containerPort: {{ .Values.service.shinyPort }}
              protocol: TCP
            {{- end}}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.storage.enableDshm }}
            - name: dshm
              mountPath: /dev/shm
            {{- end }}
            {{- if .Values.storage.enabled }}
            - name: data
              mountPath: {{ .Values.storage.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.storage.enableDshm }}
        - name: dshm
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if .Values.storage.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rstudio.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
