apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libre-chat.fullname" . }}
  labels:
    {{- include "libre-chat.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "libre-chat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "libre-chat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libre-chat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.workingDir }}
          workingDir: {{ .Values.storage.workingDir }}
          {{- else }}
          workingDir: {{ .Values.storage.mountPath }}
          {{- end }}
          {{- if .Values.image.command }}
          command:
            {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.password }}
            - name: LIBRECHAT_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  key: application-password
                  name: {{ include "libre-chat.fullname" . }}
            {{- end }}
            {{- if .Values.chatConf }}
            - name: LIBRECHAT_CONF_PATH
              value: /config/chat.yml
            {{- end }}
            {{- if .Values.confUrl }}
            - name: LIBRECHAT_CONF_URL
              value: {{ .Values.confUrl }}
            {{- end }}
            # To enable updating the image: https://github.com/kubernetes/kubernetes/issues/33664
            - name: RELEASE_DATE
              value: "{{ now }}"
            {{- range .Values.extraEnvs }}
            - name: {{ toString .name }}
              value: {{ toString .value }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.storage.enableDshm }}
            - name: dshm
              mountPath: /dev/shm
            {{- end }}
            {{- if .Values.chatConf }}
            - name: configs
              mountPath: "/config"
            {{- end }}
            {{- if .Values.storage.enabled }}
            - name: data
              mountPath: {{ .Values.storage.mountPath }}
            {{- end }}
            {{- range .Values.storage.extraStorage }}
            - name: {{ toString .name }}
              mountPath: {{ toString .mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.storage.enableDshm }}
        - name: dshm
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if .Values.chatConf }}
        - name: configs
          configMap:
            name: {{ include "libre-chat.fullname" . }}
        {{- end }}
        {{- if .Values.storage.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "libre-chat.fullname" . }}
        {{- end }}
        {{- range .Values.storage.extraStorage }}
        - name: {{ toString .name }}
          persistentVolumeClaim:
            claimName: {{ toString .name }}
            readOnly: {{ toString .readOnly }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
