{{- if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  # annotations:
  #   template.openshift.io/expose-password: "{.data['application-password']}"
  name: {{ include "libre-chat.fullname" . }}
  labels:
    {{- include "libre-chat.labels" . | nindent 4 }}
stringData:
  application-password: {{ .Values.password }}
{{- end }}