
{{- if .Values.image.addJupyterConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
data:
  # Clone git repo, then install requirements.txt and packages.txt
  jupyter_notebook_config.py: |
    import os

    git_url = os.getenv('GIT_URL', None)
    git_name = os.getenv('GIT_NAME', 'Default user')
    git_email = os.getenv('GIT_EMAIL', 'default@maastrichtuniversity.nl')

    # Preconfigure git to avoid to do it manually
    os.system('git config --global user.name "' + git_name + '"')
    os.system('git config --global user.email "' + git_email + '"')

    # os.chdir('/home/jovyan/work')

    if git_url:
        os.system('git clone --quiet --recursive ' + git_url + ' .')
        # repo_id = git_url.rsplit('/', 1)[-1].replace('.git', '')
        # os.system('git clone --quiet --recursive ' + git_url)
        # os.chdir(repo_id)

    if os.path.exists('packages.txt'):
        os.system('sudo apt-get update')
        os.system('cat packages.txt | xargs sudo apt-get install -y')

    if os.path.exists('requirements.txt'):
        os.system('pip install -r requirements.txt')

    if os.path.exists('extensions.txt'):
        os.system('cat extensions.txt | xargs -I {} jupyter {} install --user')

    if os.path.exists('environment.yml'):
        os.system('mamba env create -f environment.yml')

    if os.path.exists('environment.yaml'):
        os.system('mamba env create -f environment.yaml')
{{- end }}