apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        date: "{{ .Release.Time.Seconds }}"
        {{- include "jupyterlab.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jupyterlab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.storage.mountPath }}
          command:
            {{- toYaml .Values.image.command | nindent 12 }}
          env:
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: application-password
                  name: {{ include "jupyterlab.fullname" . }}
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: GRANT_SUDO
              value: "yes"
            - name: GIT_URL
              value: {{ .Values.gitUrl }}
            - name: GIT_NAME
              value: {{ .Values.gitName }}
            - name: GIT_EMAIL
              value: {{ .Values.gitEmail }}
            {{- range .Values.extraEnvs }}
            - name: {{ toString .name }}
              value: {{ toString .value }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configs
              mountPath: "/etc/jupyter/openshift"
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.storage.enabled }}
            - name: data
              mountPath: {{ .Values.storage.mountPath }}
            {{- end }}
            {{- range .Values.storage.extraStorage }}
            - name: {{ toString .name }}
              mountPath: {{ toString .mountPath }}
            {{- end }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "jupyterlab.fullname" . }}
        - name: dshm
          emptyDir:
            medium: Memory
        {{- if .Values.storage.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "jupyterlab.fullname" . }}
        {{- end }}
        {{- range .Values.storage.extraStorage }}
        - name: {{ toString .name }}
          persistentVolumeClaim:
            claimName: {{ toString .name }}
            readOnly: {{ toString .readOnly }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
