{{- if .Values.storage.enabled }}
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  {{- if .Values.storage.storageClass }}
  storageClassName: "{{ .Values.storage.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
