apiVersion: v1
kind: Secret
metadata:
  # annotations:
  #   template.openshift.io/expose-password: "{.data['application-password']}"
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
stringData:
  application-password: {{ .Values.password }}
